version: "3.7"

services:
  database:
    image: mongo:4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thalesmorato
      - MONGO_INITDB_ROOT_PASSWORD=senha123
